version: '3.8'

services:
  webdox-app:
    image: ahmedhassan711/webdox-app:latest
    container_name: webdox-app-container
    build:
      context: .
      target: runner
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  nginx:
    image: nginx:stable-alpine
    container_name: webdox-nginx-container
    depends_on:
      - webdox-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # âœ… will hold SSL certs
    restart: always
