version: '3.8'

services:
  webdox-app:
    image: webdox-app
    container_name: webdox-app-container
    build:
      context: .
      target: dev
    restart: always
    command: sh -c "pnpm dev"
    environment:
      - APP_PORT=${APP_PORT}
      - NODE_ENV=development
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      # ✅ only mount relevant directories
      - ./app:/app/app
      - ./components:/app/components 
      - ./content:/app/content
      - ./lib:/app/lib
      - ./public:/app/public
      - ./mdx-components.tsx:/app/mdx-components.tsx
      - ./next.config.mjs:/app/next.config.mjs
      - ./source.config.mjs:/app/source.config.mjs
      # ✅ preserve installed deps & build
      - node_modules:/app/node_modules
      - next:/app/.next
    env_file:
      - .env

volumes:
  node_modules:
  next: